import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

export const PHASE2_DIFF_FILENAME = "phase2_workspace_diff.md";
export const MAX_WORKSPACE_DIFF_BYTES = 4 * 1024 * 1024;
const FALLBACK_BASELINE_FILENAME = ".phase2_baseline.json";
const GITIGNORE_CONTENT = [
  "state.sqlite3",
  "state.sqlite3-*",
  "*.sqlite3",
  "*.sqlite3-*",
  PHASE2_DIFF_FILENAME,
  FALLBACK_BASELINE_FILENAME,
  "",
].join("\n");

export interface MemoryWorkspaceChange {
  status: string;
  path: string;
}

export interface MemoryWorkspaceDiff {
  changes: MemoryWorkspaceChange[];
  unifiedDiff: string;
}

export function hasChanges(diff: MemoryWorkspaceDiff): boolean {
  return diff.changes.length > 0 || diff.unifiedDiff.trim().length > 0;
}

export async function prepareMemoryWorkspace(root: string): Promise<void> {
  fs.mkdirSync(root, { recursive: true });
  removeWorkspaceDiff(root);
  ensureGitignore(root);
  if (gitAvailable()) {
    ensureGitRepo(root);
    return;
  }
  ensureFallbackBaseline(root);
}

export async function memoryWorkspaceDiff(root: string): Promise<MemoryWorkspaceDiff> {
  removeWorkspaceDiff(root);
  if (gitAvailable() && fs.existsSync(path.join(root, ".git"))) {
    runGit(root, "add", "-A");
    const statusOutput = runGit(root, "diff", "--cached", "--name-status", "HEAD", "--");
    const diffOutput = runGit(root, "diff", "--cached", "--no-ext-diff", "HEAD", "--");
    const changes = parseNameStatus(statusOutput);
    return { changes, unifiedDiff: diffOutput };
  }
  return fallbackWorkspaceDiff(root);
}

export async function writeWorkspaceDiff(root: string, diff: MemoryWorkspaceDiff): Promise<void> {
  const target = path.join(root, PHASE2_DIFF_FILENAME);
  fs.writeFileSync(target, renderWorkspaceDiffFile(diff));
}

export async function resetMemoryWorkspaceBaseline(root: string): Promise<void> {
  removeWorkspaceDiff(root);
  if (gitAvailable() && fs.existsSync(path.join(root, ".git"))) {
    runGit(root, "add", "-A");
    const statusOutput = runGit(root, "diff", "--cached", "--name-status", "HEAD", "--");
    if (statusOutput.trim()) {
      runGit(root, "commit", "-m", "memory phase2 baseline", ...gitIdentityArgs());
    }
    return;
  }
  writeFallbackBaseline(root);
}

function ensureGitignore(root: string): void {
  const target = path.join(root, ".gitignore");
  if (fs.existsSync(target) && fs.readFileSync(target, "utf8") === GITIGNORE_CONTENT) return;
  fs.writeFileSync(target, GITIGNORE_CONTENT);
}

function ensureGitRepo(root: string): void {
  if (!fs.existsSync(path.join(root, ".git"))) {
    runGit(root, "init", "-q");
  }
  try {
    runGit(root, "rev-parse", "--verify", "HEAD");
  } catch {
    runGit(root, "add", "-A");
    runGit(root, "commit", "--allow-empty", "-m", "memory initial baseline", ...gitIdentityArgs());
  }
}

function runGit(root: string, ...args: string[]): string {
  const env = { ...process.env, ...gitIdentityEnv() };
  const result = execFileSync("git", ["-C", root, ...args], {
    encoding: "utf8",
    env,
    stdio: ["pipe", "pipe", "pipe"],
  });
  return result;
}

function gitIdentityEnv(): Record<string, string> {
  return {
    GIT_AUTHOR_NAME: "tradex-memory",
    GIT_AUTHOR_EMAIL: "memory@tradex.local",
    GIT_COMMITTER_NAME: "tradex-memory",
    GIT_COMMITTER_EMAIL: "memory@tradex.local",
  };
}

function gitIdentityArgs(): string[] {
  return [
    "-c", "user.name=tradex-memory",
    "-c", "user.email=memory@tradex.local",
  ];
}

function gitAvailable(): boolean {
  try {
    execFileSync("git", ["--version"], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function parseNameStatus(output: string): MemoryWorkspaceChange[] {
  const changes: MemoryWorkspaceChange[] = [];
  for (const line of output.split("\n")) {
    if (!line.trim()) continue;
    const parts = line.split("\t");
    const status = parts[0].trim();
    const filePath = (parts[parts.length - 1] ?? "").trim();
    if (filePath) changes.push({ status, path: filePath });
  }
  return changes;
}

function renderWorkspaceDiffFile(diff: MemoryWorkspaceDiff): string {
  const lines = [
    "# Memory Workspace Diff",
    "",
    "Generated by tradex before Phase 2 memory consolidation. Read this file first and do not edit it.",
    "",
    "## Status",
  ];
  if (!hasChanges(diff)) {
    lines.push("- none");
    return lines.join("\n") + "\n";
  }
  for (const change of diff.changes) {
    lines.push(`- ${change.status} ${change.path}`);
  }
  lines.push("", "## Diff", "", "```diff");
  lines.push(boundedDiff(diff.unifiedDiff));
  lines.push("```");
  return lines.join("\n").trimEnd() + "\n";
}

function boundedDiff(value: string): string {
  const encoded = Buffer.from(value, "utf8");
  if (encoded.length <= MAX_WORKSPACE_DIFF_BYTES) return value.replace(/\n$/, "");
  const clipped = truncateUtf8ByBytes(value, MAX_WORKSPACE_DIFF_BYTES);
  return clipped.replace(/\n$/, "") + `\n\n[workspace diff truncated at ${MAX_WORKSPACE_DIFF_BYTES} bytes]`;
}

function truncateUtf8ByBytes(value: string, maxBytes: number): string {
  let used = 0;
  let result = "";
  for (const char of value) {
    const bytes = Buffer.byteLength(char, "utf8");
    if (used + bytes > maxBytes) break;
    result += char;
    used += bytes;
  }
  return result;
}

function removeWorkspaceDiff(root: string): void {
  try {
    fs.unlinkSync(path.join(root, PHASE2_DIFF_FILENAME));
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}

function ensureFallbackBaseline(root: string): void {
  const target = path.join(root, FALLBACK_BASELINE_FILENAME);
  if (!fs.existsSync(target)) writeFallbackBaseline(root);
}

function writeFallbackBaseline(root: string): void {
  fs.writeFileSync(
    path.join(root, FALLBACK_BASELINE_FILENAME),
    JSON.stringify(snapshotFiles(root), null, 0),
  );
}

function fallbackWorkspaceDiff(root: string): MemoryWorkspaceDiff {
  const baselinePath = path.join(root, FALLBACK_BASELINE_FILENAME);
  let baseline: Record<string, string> = {};
  if (fs.existsSync(baselinePath)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(baselinePath, "utf8"));
      if (parsed && typeof parsed === "object") {
        baseline = Object.fromEntries(
          Object.entries(parsed).map(([k, v]) => [String(k), String(v)]),
        );
      }
    } catch { /* ignore */ }
  }

  const current = snapshotFiles(root);
  const allPaths = [...new Set([...Object.keys(baseline), ...Object.keys(current)])].sort();
  const changed = allPaths.filter((p) => baseline[p] !== current[p]);
  const changes: MemoryWorkspaceChange[] = changed.map((p) => ({
    status: !(p in baseline) ? "A" : !(p in current) ? "D" : "M",
    path: p,
  }));

  return { changes, unifiedDiff: renderFallbackUnifiedDiff(baseline, current, changed) };
}

function snapshotFiles(root: string): Record<string, string> {
  const files: Record<string, string> = {};
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (ignoredForSnapshot(root, full, entry.name)) continue;
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile()) {
        try {
          files[path.relative(root, full).replace(/\\/g, "/")] = fs.readFileSync(full, "utf8");
        } catch { /* skip binary */ }
      }
    }
  };
  walk(root);
  return files;
}

function ignoredForSnapshot(root: string, full: string, name: string): boolean {
  if (name === ".git" || name === "__pycache__" || name.startsWith(".")) return true;
  if (name === PHASE2_DIFF_FILENAME) return true;
  if (name.endsWith(".sqlite3") || name.includes(".sqlite3-")) return true;
  return false;
}

function renderFallbackUnifiedDiff(
  before: Record<string, string>,
  after: Record<string, string>,
  paths: string[],
): string {
  const chunks: string[] = [];
  for (const p of paths) {
    const oldLines = (before[p] ?? "").split("\n");
    const newLines = (after[p] ?? "").split("\n");
    if (!(p in before)) {
      chunks.push(`--- /dev/null\n+++ b/${p}\n` + newLines.map((l) => `+${l}`).join("\n"));
    } else if (!(p in after)) {
      chunks.push(`--- a/${p}\n+++ /dev/null\n` + oldLines.map((l) => `-${l}`).join("\n"));
    } else {
      chunks.push(`--- a/${p}\n+++ b/${p}\n@@ modified @@\n`);
    }
  }
  return chunks.join("\n");
}
